import type { Metadata } from "next";
import "./globals.css";
import { DEV_NAME } from "@/utils/constants";

export const metadata: Metadata = {
  title: `${DEV_NAME}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {children}
      </body>
    </html>
  );
}
